apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: hsci-datascience-notebook-ephemeral
  template: hsci-datascience-notebook-ephemeral
message: |-

metadata:
  annotations:
    description: Jupyter datascience notebook with git LFS support, preloaded libraries and RSA key injection (ephemeral version)
    iconClass: fa fa-bar-chart
    openshift.io/display-name: HSCI data science notebook (ephemeral storage)
    openshift.io/documentation-url: https://github.com/hsci-r/hsci-datascience-notebook
    openshift.io/support-url: https://heldig.fi/hsci/
    openshift.io/long-description:
    openshift.io/provider-display-name: HSCI
    tags: datascience-notebook
    template.openshift.io/bindable: "false"
  name: hsci-datascience-notebook-ephemeral

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-password-hash
    type: Opaque
    stringData:
      password_hash: ${PASSWORD_HASH}

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      ports:
        - port: 8888
          targetPort: 8888
          protocol: TCP
          name: http
      selector:
        deploymentconfig: ${NAME}

  - apiVersion: v1
    kind: Route
    metadata:
      name: ${NAME}
      annotations:
        template.openshift.io/expose-uri: http://{.spec.host}
    spec:
      host: ${NAME}.${APPLICATION_DOMAIN_SUFFIX}
      path: /
      to:
        kind: Service
        name: ${NAME}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      port:
        targetPort: http

  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the appliation image
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
      tags:
        - from:
            kind: DockerImage
            name: ${DOCKER_IMAGE}
          importPolicy:
            scheduled: true
          name: ${DOCKER_IMAGE_TAG}
          referencePolicy:
            type: Source

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        description: HSCI datascience notebook
        template.alpha.openshift.io/wait-for-ready: "true"
      name: ${NAME}
    spec:
      selector:
        app: ${NAME}
        deploymentconfig: ${NAME}
      strategy:
        type: Recreate
      # We actually don't want an image change to overwrite whatever we've been doing on running instances, so no triggers
      #    triggers:
      #      - type: ImageChange
      #        imageChangeParams:
      #          automatic: true
      #          containerNames:
      #            - ${NAME}
      #          from:
      #            kind: ImageStreamTag
      #            name: ${NAME}:${DOCKER_IMAGE_TAG}
      #      - type: ConfigChange
      replicas: 1
      template:
        metadata:
          labels:
            app: ${NAME}
            deploymentconfig: ${NAME}
        spec:
          containers:
            - name: ${NAME}
              image: ${NAME}:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 8888
              # We actually don't want the pod to autorestart automatically either
              #livenessProbe:
              #  httpGet:
              #    path: /
              #    port: 8888
              #  initialDelaySeconds: 10
              #  timeoutSeconds: 15
              resources:
                requests:
                  cpu: 200m
                  memory: 6Mi
              env:
                - name: PASSWORD_HASH
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-password-hash
                      key: password_hash
                - name: SSH_RSA_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${PRIVATE_KEY_REF}
                      key: ssh-privatekey

####################

parameters:
  - description: Unique identifier for your instance.
    displayName: Application Name
    name: NAME
    required: true

  - description: Password hash for logging into the notebook
    displayName: Password hash
    name: PASSWORD_HASH
    required: true

  - description: Reference to the OpenShift secret that contains an RSA private key to be injected into the container
    displayName: RSA key secret name
    name: PRIVATE_KEY_REF
    required: true

  - description: The exposed hostname suffix that will be used to create routes for app
    displayName: Application Hostname Suffix
    name: APPLICATION_DOMAIN_SUFFIX
    required: true
    value: rahtiapp.fi

  - description: Docker image to use
    displayName: Docker image
    name: DOCKER_IMAGE
    required: true
    value: quay.io/hsci/hsci-datascience-notebook

  - description: Docker image tag to use
    displayName: Docker image tag
    name: DOCKER_IMAGE_TAG
    required: true
    value: latest
